name: Simulate Terraform Plan

on:
  workflow_dispatch:
    inputs:
      workflow_id:
        required: true
        description: "The identifier of the tf_workflow entity"
        type: string

jobs:
  simulate-tf-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Port Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'${{ secrets.PORT_CLIENT_ID }}'",
              "clientSecret": "'${{ secrets.PORT_CLIENT_SECRET }}'"
          }' | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Simulate Terraform Plan Markdown
        run: |
          cat <<EOF > plan.md
          ## Terraform Plan Summary

          \`\`\`diff
          + resource "aws_instance" "example" {
              ami           = "ami-12345678"
              instance_type = "t3.medium"
              tags = {
                Name = "example-instance"
              }
            }
          \`\`\`

          _This is a simulated plan. No infrastructure changes have been made._
          EOF

      - name: Update tf_workflow Entity in Port
        run: |
          MARKDOWN_CONTENT=$(cat plan.md | jq -Rs .)
          curl -s -X PATCH "https://api.getport.io/v1/blueprints/tf_workflow/entities/${{ inputs.workflow_id }}" \
          -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
          {
            "properties": {
              "status": "planned",
              "plan": $MARKDOWN_CONTENT
            }
          }
          EOF
